export const totalCount ={ 
        "Condense milk":20,
        "Pineapple":10,
        "Nurishment":60,
        "Agave":80,
        "Guinness":50, 
        "Carrot":10,
        "Oat Milk":20,
        "Bottle":100,
        "Seamoss":5,
        "V Condense milk":25,
        "B Oat milk":10,
        "Coco cream":15, 
        "Pumpkin":50,
}